### ISSUE TITLE
Is there a purpose? 

### ISSUE THREAD

**Issue by joezimjs** [cmartin81/decorator-promise#1]
I know that Async Functions aren't guaranteed to show up right now, but wouldn't it just be easier to add the `async` keyword in front of the function?

**Comment by cmartin81** [comment]
I have not tried out the async keyword, but that is on my todo list (generators is also on the same list). I have been using promises for a while and it was one of the first module I though could be a nice plugin for the decorator-wrap module.

Since the name is decorator-promise I will not change it to use the async keyword. 
But if you need (or want) to use the async keyword then you can create a new module (decorator-async) and publish it.

**Comment by joezimjs** [comment]
Async Functions wouldn't need a decorator at all, just a keyword. If I think about it, though, this decorator could end up with cleaner code than async functions after Babel is done with it, so it isn't totally useless. I was just thinking that you were solving a problem using ES2016 code that is already solved in ES2016 in another simpler way.
